#!/bin/sh

bun run prettier -c app/javascript spec/javascript && bun test && bundle exec herb analyze app/views && bundle exec rubocop && RUBYOPT="-W0" bundle exec erb_lint --lint-all && bundle exec bundle audit --update && bundle exec brakeman -q -w2 && bundle exec parallel_rspec -- -t ~js -t ~ocr -- spec && bundle exec rspec -t js -t ocr